# Generated by Django 5.1.3 on 2024-11-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='image',
            field=models.ImageField(upload_to='bookimage'),
        ),
    ]
