# Generated by Django 5.1.3 on 2024-11-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0002_alter_library_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrental',
            name='address',
        ),
        migrations.AddField(
            model_name='bookrental',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
