# Generated by Django 5.1.3 on 2024-11-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0007_product_alter_cartitem_product_delete_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
    ]
