# Generated by Django 5.1.3 on 2024-11-25 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0008_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
